<a href="https://colab.research.google.com/github/LiliiaPavl/PavlovaLiliia/blob/main/9_1_Manipulating_data_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [1]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [2]:
res = np.array([1, 2, 3, 4, 5]) # TODO

print(res)

[1 2 3 4 5]


In [3]:
res2 = np.arange(1, 6) # TODO

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [4]:
res3 = np.random.randint(1, 101, size=(3, 5))# TODO

print(res3)

[[36 82  7 98 46]
 [33 97  2 84 81]
 [41  6 92 83 87]]


### Task 3

Print the first row of array `res3`.

In [9]:
first_row = res3[0]
print(first_row)

[36 82  7 98 46]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [10]:
last_column_on_first_row = res3[0, -1]
print(last_column)

46


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [11]:
# Min
second_column = res3[:, 1]
res_min = second_column.min()
print('min =', res_min)

min = 6


In [12]:
# Max
second_column = res3[:, 1]
res_max = second_column.max()
print('max =', res_max)

max = 97


In [13]:
# Sum
second_column = res3[:, 1]
res_sum = second_column.sum()
print('sum =', res_sum)

sum = 185


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [15]:
x = np.arange(0, 1.1, 0.1)
f_x = np.exp(2 * x)

print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [16]:
url = "https://web.stanford.edu/class/cs102/datasets/Titanic.csv"

df = pd.read_csv(url)
print(df.head())


        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  Southampton      yes  
3  53.1000  Southampton      yes  
4   8.0500  Southampton       no  


### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [25]:
print(df.columns)

Index(['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked',
       'survived'],
      dtype='object')


In [26]:
print(df.head(10))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  So

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [28]:
df['full name'] = df['first'] + ' ' + df['last']

print(df.head(10))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  \
0   7.2500  Southampton       no   
1  71.2833    Cherbourg      yes   
2   7.9250 

### Task 10

Remove the two original columns - last, first.

In [29]:
df = df.drop(columns=['last', 'first'])
print(df.head(10))

  gender   age  class     fare     embarked survived  \
0      M  22.0      3   7.2500  Southampton       no   
1      F  38.0      1  71.2833    Cherbourg      yes   
2      F  26.0      3   7.9250  Southampton      yes   
3      F  35.0      1  53.1000  Southampton      yes   
4      M  35.0      3   8.0500  Southampton       no   
5      M   NaN      3   8.4583   Queenstown       no   
6      M  54.0      1  51.8625  Southampton       no   
7      M   2.0      3  21.0750  Southampton       no   
8      F  27.0      3  11.1333  Southampton      yes   
9      F  14.0      2  30.0708    Cherbourg      yes   

                                           full name  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                            Mr. William Henry Allen  
5                                    Mr. James Moran 

### Task 11

Calculate the total number of survivors in the dataset.

In [49]:
total_survivors = df['survived'].map({'yes': 1, 'no': 0}).sum()

print("Total number of survivors:", total_survivors)

Total number of survivors: 0.0
